### ISSUE TITLE
Should we make every component match unique?

### ISSUE THREAD

**Issue by bcipolli** [bcipolli/lateralized-components#22]
@bcipolli: 
>Allow re-using matches. For example, both has left and right finger movements as separate components. We get the RL components and match them, but then can only match up with one of the two both components.
>
>Restricting usage of one component also affects lateralized functions like language. Nothing matces, so it grabs some randomly "similar" component.
>
>The language issue also affects similarity score. Since that RL match is not compelling, it's going to decrease the similarity score to the language component in both. So perhaps computing similarity between RL and both by: matching R to both:R, L to both:L, and allowing reuse of matches (and then visualizing any components never chosen as the best match).

@atsuch:
>As for allowing to reuse matches, I thought about it too, just hadn't got around to discuss it with you. Whether we do comparisons your way (RL to both) or my way (R- or L- only to both), I wasn't sure if we should be forcing one-to-one matching for all the components. We are hypothesizing that some wb components will have good match than others, depending on how much the interhemispheric interactions are affecting the wb component. That's why I wanted to be able to compare match scores not just by rows but across the whole matrix.

**Comment by atsuch** [comment]
I liked doing R- or L-only to both rather than RL to both precisely because for any lateralized whole-brain component will have a hard time getting a good match with artificially concatenated RL. By doing R- or L-only to both, some lateralized wb components will have a good match with one hemi but not the other, and we get to see that information by comparing R- to both and L-to both matrices. 

Separately from that issue, I was thinking about whether we should be forcing one-to-one matches. I was actually playing with adding a histogram of all the dissimilarity scores to see whether we can find a good cut-off of scores to determine match vs non-match, because I'm not sure how meaningful it is to grab the best match when a component really doesn't have any good corresponding component. On the other hand, one wb component could split up in two separate sub-components in R- or L- only, in which case that component might have two different more or less equally good (but not perfect) matches.

So my thought was to either to come up with a threshold based on the distribution of the scores or just take the best 20 matches, for example, allowing for reusing of components...

**Comment by bcipolli** [comment]
Sounds good :+1: . I will also open an issue to rename `both` to `wb` ;)

**Comment by bcipolli** [comment]
Again, this will be made easier by an interactive plot (e.g. #21 ). If you can make a PR with a histogram of similarity scores, I think that'd be cool!

**Comment by atsuch** [comment]
I'm going to close this since the main.py in newRLmatch now let you choose unique (i.e. one-to-one matching) or allow reusing of matches with --force_match option.
