### ISSUE TITLE
QC : potentially bad images

### ISSUE THREAD

**Issue by bcipolli** [bcipolli/lateralized-components#40]
Collection 1385; image 19228 is an example, others look similarly.
![image](https://cloud.githubusercontent.com/assets/4072455/19311155/f524059a-9041-11e6-9236-53f52e38a029.png)

Collection 1003, image 13892 is an example. Metadata does not indicate parcellation.
![image](https://cloud.githubusercontent.com/assets/4072455/19311234/51dd81da-9042-11e6-9be1-f8b180dc66c3.png)

Image 13920 is all white: 
![image](https://cloud.githubusercontent.com/assets/4072455/19311271/79a5ecd4-9042-11e6-9c7b-4cb4f46a1faf.png)

**Comment by bcipolli** [comment]
Some suggestions:

* Check the variance of voxels / # unique values, to remove parcellations / maps.
* Check local correlations should be high, to detect noise.

**Comment by atsuch** [comment]
Thank you @bcipolli! The collection 1003 was actually among the manually-removed collections in our previous code (in nilearn_ext/dataset.py):

`    # Also remove bad collections
    bad_collects = [367,   # Single image w/ large uniform area value > 0
                    1003,  # next three collections contain stat maps on
                    1011,  # parcellated brains. Likely causes odd-looking
                    1013]  # ICA component`

But of course it would be nice to detect them automatically rather than having to manually check every time we get new images...

There are only one parcellated image that didn't get filtered out, but there could be more in the future, if people use parcellated brains to perform stats, rather than doing voxel-based stats, to increase power. It doesn't get filtered out because technically it's statistical map, and not an atlas or parcellation. It's not very common so far but eventually Neurovault may need a new meta-data field indicating whether the stats are voxel-based or other parcellation schemes.

**Comment by bcipolli** [comment]
Fixed by @bcipolli
